### ISSUE TITLE
Extract nested field as an attribute not a relation

### ISSUE THREAD

**Issue by Aleyasen** [torodb/stampede#217] opened 2018-07-18 05:43 UTC
@ahachete, thanks for the great open source effort, it's impressive! 
I am using stampede in a project, but since our schema has many nested fields, it will create a lot of tables. Since in theory, stampede can generate nested fields as attributes not as new relations, I am wondering what was the design decision behind this implementation? 
And more importantly, is there any configuration that can change the mode to create attribute instead relation for nested fields?

Thanks a lot.

**Comment by ahachete** [comment] 2018-10-03 11:58
Hi @Aleyasen By design, if a nested field is a document, it will require a separate table. A large number of tables should not be scary. It is, after all, what you'd probably design manually if you would create the tables yourself.

There's currently no way to change this mapping. But nobody prevents you to create SQL VIEWs or functions to "group" those tables into the structure you want! :)

Closing issue as a non-issue, feel free to reopen if you consider otherwise.

**Closed as completed by ahachete** 2018-10-03 11:58 UTC
